language: rust
rust:
  - stable
  - beta
  - nightly

install:
  - mkdir ~/lib
  - curl -L $(sed 's/"//g' Cargo.toml | awk '/bear-lib-terminal.*/ {print "https://github.com/nabijaczleweli/BearLibTerminal.rs/releases/download/v" $3 "/libBearLibTerminal.so"}') -o ~/lib/libBearLibTerminal.so

script:
  - LD_PRELOAD=~/lib/libBearLibTerminal.so LD_LIBRARY_PATH="~/lib:$LD_LIBRARY_PATH" LIBRARY_PATH=~/lib cargo build --verbose
  - LD_PRELOAD=~/lib/libBearLibTerminal.so LD_LIBRARY_PATH="~/lib:$LD_LIBRARY_PATH" LIBRARY_PATH=~/lib cargo test --verbose
